;===============================================================================
;
;       .o.        .oooooo..o   .oooooo.   ooooo ooooo 
;      .888.      d8P'    `Y8  d8P'  `Y8b  `888' `888' 
;     .8"888.     Y88bo.      888           888   888  
;    .8' `888.     `"Y8888o.  888           888   888  
;   .88ooo8888.        `"Y88b 888           888   888  
;  .8'     `888.  oo     .d8P `88b    ooo   888   888  
; o88o     o8888o 8""88888P'   `Y8bood8P'  o888o o888o 
;
; ASCII Control Characters
;-------------------------------------------------------------------------------
; Copyright (C),2019-2020 Andrew John Jacobs.
; All rights reserved.
;
; This work is licensed under a Creative Commons Attribution NonCommercial-
; ShareAlike 4.0 International License.
;
; See here for details:
;
;	https://creativecommons.org/licenses/by-nc-sa/4.0/
;
;===============================================================================
; Notes:
;
;-------------------------------------------------------------------------------

NUL		.equ	$00
SOH		.equ	$01
STX		.equ	$02
ETX		.equ	$03
EOT		.equ	$04
ENQ		.equ	$05
ACK		.equ	$06
BEL		.equ	$07
BS		.equ	$08
TAB		.equ	$09
LF		.equ	$0a
VT		.equ	$0b
FF		.equ	$0c
CR		.equ	$0d
SO		.equ	$0e
SI		.equ	$0f
DLE		.equ	$10
DC1		.equ	$11
DC2		.equ	$12
DC3		.equ	$13
DC4		.equ	$14
NAK		.equ	$15
SYN		.equ	$16
ETB		.equ	$17
CAN		.equ	$18
EM		.equ	$19
SUB		.equ	$1a
ESC		.equ	$1b
FS		.equ	$1c
GS		.equ	$1d
RS		.equ	$1e
US		.equ	$1f

DEL		.equ	$7f
