#===============================================================================
# OS/65 Build Definitions
#-------------------------------------------------------------------------------
# Copyright (C)2016-2017 HandCoded Software Ltd.
# All rights reserved.
#
# This work is made available under the terms of the Creative Commons
# Attribution-NonCommercial 2.0 license. Open the following URL to see the
# details.
#
# http://creativecommons.org/licenses/by-nc/2.0/
#-------------------------------------------------------------------------------
#
# Notes:
#
#
#
#===============================================================================
# Revision History:
#
# 2016-12-31 AJ Initial version
#-------------------------------------------------------------------------------

include	../MakeDefns

#===============================================================================
# Targets
#-------------------------------------------------------------------------------
	

